from django.urls import path

from .stripe_views import CreateStripeCheckoutSessionView, StripeWebhookView
from .views import (
    BillingAddressViews,
    CartItemViews,
    CartViews,
    CategoryViews,
    ColorViews,
    ContactMessageViews,
    CouponViews,
    DistrictsViews,
    HeroSectionViews,
    ItemColorViews,
    ItemDetailViews,
    ItemImageViews,
    ItemSizeViews,
    ItemTypeViews,
    ItemViews,
    NewArrivalBannerImageListView,
    NewArrivalBannerView,
    OrderItemViews,
    OrderViews,
    PaymentViews,
    RatingViews,
    RefundViews,
    SiteSettingView,
    SizeViews,
    SliderViews,
)

urlpatterns = [
    path("items/", ItemViews.as_view(), name="items"),
    path("items/<int:pk>/", ItemDetailViews.as_view(), name="item-detail"),
    path("districts/", DistrictsViews.as_view(), name="districts"),
    path("categories/", CategoryViews.as_view(), name="categories"),
    path("item-types/", ItemTypeViews.as_view(), name="item-types"),
    path("sizes/", SizeViews.as_view(), name="sizes"),
    path("ratings/", RatingViews.as_view(), name="ratings"),
    path("colors/", ColorViews.as_view(), name="colors"),
    path("item-images/", ItemImageViews.as_view(), name="item-images"),
    path("item-sizes/", ItemSizeViews.as_view(), name="item-sizes"),
    path("item-colors/", ItemColorViews.as_view(), name="item-colors"),
    path("sliders/", SliderViews.as_view(), name="sliders"),
    path("hero-sections/", HeroSectionViews.as_view(), name="hero-sections"),
    path("billing-addresses/", BillingAddressViews.as_view(), name="billing-addresses"),
    path("payments/", PaymentViews.as_view(), name="payments"),
    path("coupons/", CouponViews.as_view(), name="coupons"),
    path("refunds/", RefundViews.as_view(), name="refunds"),
    path("carts/", CartViews.as_view(), name="carts"),
    path("carts/<int:pk>/", CartItemViews.as_view(), name="cart-detail"),
    path("contacts/", ContactMessageViews.as_view(), name="contacts"),
    path("orders/", OrderViews.as_view(), name="orders"),
    path("order-items/", OrderItemViews.as_view(), name="order-items"),
    path(
        "stripe/create-checkout-session/",
        CreateStripeCheckoutSessionView.as_view(),
        name="stripe-create-checkout",
    ),
    path("stripe/webhook/", StripeWebhookView.as_view(), name="stripe-webhook"),
    path(
        "new-arrivals-banner/",
        NewArrivalBannerView.as_view(),
        name="new-arrivals-banner",
    ),
    path(
        "new-arrivals-banner/images/",
        NewArrivalBannerImageListView.as_view(),
        name="new-arrivals-banner-images",
    ),
    path(
        "site-settings/",
        SiteSettingView.as_view(),
        name="site-settings",
    ),
]
