# Generated by Django 6.1 on 2026-09-01 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0006_customusermodel_otp_customusermodel_otp_expiry_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customusermodel",
            name="OTP",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
