# Generated by Django 5.2.3 on 2025-08-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('offer', models.CharField(max_length=255)),
                ('button_1_Text', models.CharField(max_length=20)),
                ('button_2_Text', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='HeroSection/')),
            ],
        ),
    ]
