# Generated by Django 5.2.3 on 2025-08-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='button_1_navigate_url',
            field=models.URLField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='herosection',
            name='button_2_navigate_url',
            field=models.URLField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to='ImageSlider/'),
        ),
    ]
