# Generated by Django 6.1 on 2026-09-05 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_vendor_item_vendor"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewArrivalBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="NEW ARRIVALS", max_length=200)),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        default="Curabitur luctus ipsum eget convallis",
                        max_length=300,
                    ),
                ),
                (
                    "discount_percent",
                    models.CharField(blank=True, default="50%", max_length=50),
                ),
                (
                    "discount_text",
                    models.CharField(
                        blank=True, default="ON ALL PRODUCTS", max_length=100
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "New Arrival Banner",
                "verbose_name_plural": "New Arrival Banners",
            },
        ),
        migrations.CreateModel(
            name="NewArrivalBannerImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_name",
                    models.CharField(help_text="Image name or title", max_length=200),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="banners/"),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional external image URL if not uploaded directly",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "link_url",
                    models.CharField(
                        blank=True,
                        default="/products",
                        help_text="Target URL when clicking this slide",
                        max_length=255,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "banner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="shop.newarrivalbanner",
                    ),
                ),
            ],
            options={
                "verbose_name": "New Arrival Banner Image",
                "verbose_name_plural": "New Arrival Banner Images",
                "ordering": ["order", "id"],
            },
        ),
    ]
