# Generated by Django 6.1 on 2026-09-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_newarrivalbanner_newarrivalbannerimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(blank=True, default="MAXSHOP", max_length=100),
                ),
                (
                    "hotline_label",
                    models.CharField(
                        default="HOTLINE:",
                        help_text="Hotline title/label",
                        max_length=50,
                    ),
                ),
                (
                    "hotline_number",
                    models.CharField(
                        default="(801) 2345 - 6789",
                        help_text="Customer service hotline phone number",
                        max_length=100,
                    ),
                ),
                (
                    "announcement_badge",
                    models.CharField(blank=True, default="This Week", max_length=50),
                ),
                (
                    "announcement_text",
                    models.CharField(
                        blank=True, default="Maecenas faucibus mollis", max_length=255
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Setting",
                "verbose_name_plural": "Site Settings",
            },
        ),
    ]
